# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
            
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      - run:
          name: Run Tests with Sonar Coverage
          command: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test

      - run:
          name: Update Sonar Analysis
          command: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=wasiqb-github -Dsonar.login=2a3b543fa174cd6f6dab293da326d9aa62473316